package springdemo.user;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.PersistenceConstructor;

class User {
    @Id
    private final Long id;
    private final String username;
    private final String email;

    User(String username, String email) {
        this.email = email;
        this.id = null;
        this.username = username;
    }

    @PersistenceConstructor
    User(Long id, String username, String email) {
        this.id = id;
        this.username = username;
        this.email = email;
    }

    /**
     * This is needed when the ID is autogenerated by the database
     */
    public User withId(Long id) {
        return new User(id, this.username, email);
    }

    public String getUsername() {
        return username;
    }

    public Long getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }
}
